version: '3'
services:
    app:
        build: .
        ports:
            - "8081:5000"
    nginx:
        image: "lab43/app"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./media:/www/media
        depends_on: 
          - app
        ports:
          - "80:80"